### ISSUE TITLE
Elapsed time & frames origin

### ISSUE THREAD

**Issue by Press-OK** [Limeth/obs-shaderfilter-plus#10]
Hi there,

I am trying to get a uniform of elapsed time from the moment that the source becomes visible. For example:
```
float4 render(float2 uv) {
    if (builtin_elapsed_time > 2.0) {
        return float4(1.0, 1.0, 1.0, 1.0);
    }
    return image.Sample(builtin_texture_sampler, uv);
}
```
Should render white after 2 seconds if I understood correctly. Instead, it always renders white. I also tried using `builtin_frame`.
I'm trying to get the shader to restart when the source/parent scene becomes visible.

Thanks!

**Comment by Limeth** [comment]
Hello, the problem is that the `builtin_elapsed_time` uniform variable is tracking the time since _creation_, not since it became _visible_. This seems like a simple feature to add, however.

**Comment by Limeth** [comment]
Added in v0.2.0.
