### ISSUE TITLE
shader that shakes the image

### ISSUE THREAD

**Issue by javismiles** [Limeth/obs-shaderfilter-plus#11]
good day, I'm trying to use shaderfilter plus to create a shader that shakes the image coming from the camera, I have created some glsl shaders in the past for touchdesigner but I cannot manage to create one for shaderfilter plus, i get errors all the time; could anybody point me to a simple version of a shader that would shake the image continuously at a certain editable rhythm and that I can then tweak in here, thank you so much

**Comment by Limeth** [comment]
Hello Javis! Thanks for your interest in the plugin. Have you maybe tried looking for a similar shader at shadertoy.com that would suit your needs? It should not be too difficult to adapt it from there. If you are getting any specific errors, I might be able to help with those.

**Comment by javismiles** [comment]
hey thank you so much for your reply, look I found exactly what I need to do, its already made here, in previous version of the plugin:
https://github.com/Oncorporation/obs-shaderfilter/blob/master/data/examples/shake.effect

could you help me adapt this one to work on OBS windows 10? I also tried to switch from direct11 to opengl, but no luck, thank you so much :)

**Comment by Limeth** [comment]
If OBS ShaderFilter already has that effect, the easiest solution would be to just use OBS ShaderFilter instead. That plugin is perfectly functional, and if you don't need the additional features (like having access to the audio frequency spectrum) it should work just fine.

**Comment by javismiles** [comment]
I get you, thing is there are no binaries to install for ShaderFilter, one has to build it from source and Im getting errors building it thats why I couldnt test that one there

**Comment by Limeth** [comment]
They are at the OBS forums: https://obsproject.com/forum/resources/obs-shaderfilter.775/

**Comment by javismiles** [comment]
thank you so much Limeth,
yes indeed just found it and installed it successfully,
and then I go to load the one I need which is this one:
https://raw.githubusercontent.com/Oncorporation/obs-shaderfilter/master/data/examples/shake.effect

I need to shake the image coming from webcam,

so I apply that one, and no errors, and options and sliders appear,
but image from webcam disappears completely in obs so nothing shows up,

is there any special thing to do to apply this shake effect to the webcam input? I will ask the person of that repo

thank you again Limeth :)

**Comment by javismiles** [comment]
Good day, 
so I managed to get the movement that I need, and it works in the other plugin;
however the other plugin is pretty inestable, it crashes often;
would anybody be able to translate this very simple code to make it work in your plugin? that would be great as the other plugin is quite inestable:

`uniform float4x4 ViewProj;
uniform texture2d image;
uniform float local_time;



uniform float speed = 0.79;
uniform float cucu = 0.19;

sampler_state textureSampler {
	Filter    = Linear;
	AddressU  = Border;
	AddressV  = Border;
	BorderColor = 00000000;
};

struct VertData {
	float4 pos : POSITION;
	float2 uv  : TEXCOORD0;
};

VertData mainTransform(VertData v_in)
{
	VertData vert_out;

	float3 pos = v_in.pos.xyz;

	float amplitude=50.0;
	float speedmove=0.5;
	float scaling=0.6; // less than 1 scales up, more than 1 scales down, but from top left corner always

    // esto es offset de posicion
	float ori = local_time * speedmove;	

	float t=sin(ori)*amplitude;
	float t2=sin(ori*1.5)*amplitude;

	float off_x=0.0-t/1.0; 
	float off_y=0.0-t2/1.0;
	float off_z=0.0;

	float3 newpos = float3(v_in.pos.x+off_x, v_in.pos.y+off_y, v_in.pos.z+off_z);
	vert_out.pos = mul(float4(newpos,1), ViewProj);

	v_in.uv.x=v_in.uv.x+0.4;
	v_in.uv.y=v_in.uv.y+0.4;

	vert_out.uv = v_in.uv * scaling; 
	return vert_out;

}

float4 mainImage(VertData v_in) : TARGET
{
	return image.Sample(textureSampler, v_in.uv);
}

technique Draw
{
	pass
	{
		vertex_shader = mainTransform(v_in);
		pixel_shader  = mainImage(v_in);
	}
}`

the only thing left to do is to crop the parts of image that go beyond the original borders, but if somebody helps me make that code work on your plugin I will then research to see how to do the crop as well

thank you :)

**Comment by javismiles** [comment]
thank you again for your help, I managed to sort it out by modifying the shake filter provided by Charles and then scaling up the parent entity,
thank you and best wishes
