### ISSUE TITLE
Open "Discussions" to share ShaderFilter-Plus shaders?

### ISSUE THREAD

**Issue by MarioMey** [Limeth/obs-shaderfilter-plus#16]
I know that @NetherEran wrote some nice shaders to use with this plugin. I transported some others... it would be greate to have a place to share this kind of shaders.

If someone needs help about transporting from another shaders platforms, we can use Discussion also for it.

**Comment by Limeth** [comment]
If you make a pull request adding those shaders into the `example` directory, I can merge it, if they work. It is not as accessible of a distribution mechanism as shadertoy is, but I'm not really sure what else could be done other than a website with a forum, but that seems like overkill to me.

**Comment by MarioMey** [comment]
I'll do it!

I said "Discussions" as in [upgradeQ cheatcode github](https://github.com/upgradeQ/OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API/discussions). Because, talking about shaders and/or how to transport them are not issues or bugs.

**Comment by Limeth** [comment]
Oh, I wasn't even aware this was possible in GitHub, I'll look into it!

**Comment by Limeth** [comment]
@MarioMey Alright, I enabled discussions. The ["show and tell"](https://github.com/Limeth/obs-shaderfilter-plus/discussions/categories/show-and-tell) category is probably best for sharing shaders.
