### ISSUE TITLE
How to install on Linux?

### ISSUE THREAD

**Issue by TheOddler** [Limeth/obs-shaderfilter-plus#30]
How do I install this properly?

I places the `libobs_shaderfilter_plus_linux_x64.so` file in my `home/.config/obs-studio/plugins` folder. That's the same folder I have the `move-transition` plugin in. But no shaderfilter shows up.

So why is this plugin not showing up in my filters?

**Comment by MarioMey** [comment]
Try to take move-transitions file out of that folder and start OBS.

- If that plug-in is not installed, the problem is the ShaderFilterPlus file.
- If the plug-in is yet there, the problem is the path. File must be located somewhere else.

**Comment by MarioMey** [comment]
Here is mine: `/home/mariomey/apps/obs-010/obs-plugins/64bit`. To understand better, executable `obs` file is in `/home/mariomey/apps/obs-010/bin/64bit`.

Also, I don't have `/home/mariomey/.config/obs-studio/plugins` folder. I do have `/home/mariomey/obs-studio-a/plugin_config` where plugins saves config files and cache. But there are not plugins bin files.

**Comment by Limeth** [comment]
It may be possible to see whether the plugin is loading if you take a look in the OBS log, but I am not certain of it. Did you get it working?

**Comment by TheOddler** [comment]
Placing it in a different folder like Mario suggested seems to have worked! Thanks!
