### ISSUE TITLE
Empty Folders

### ISSUE THREAD

**Issue by Peckster95** [Limeth/obs-shaderfilter-plus#34]
A friend and I have both downloaded this and when trying to implement it in OBS the folders are empty so we can't apply any shaders

**Comment by MarioMey** [comment]
What folders? Plugin is a file and depends on O.S. For Linux is [libobs_shaderfilter_plus_linux_x64.so](https://github.com/Limeth/obs-shaderfilter-plus/releases/download/v0.3.1/libobs_shaderfilter_plus_linux_x64.so) and for Win is [obs_shaderfilter_plus_windows_x64.dll](https://github.com/Limeth/obs-shaderfilter-plus/releases/download/v0.3.1/obs_shaderfilter_plus_windows_x64.dll). They are files, not folders. You have to put that file in the correct folder... and dependes on where do you have OBS installed.

I have a portable OBS (built by me) and I have that folder in:

`/home/mariomey/apps/obs-010/obs-plugins/64bit`
Here:
![imagen](https://user-images.githubusercontent.com/4954109/165359796-39a0037d-8e36-498d-95f8-fc1931ae9caa.png)

**Comment by Limeth** [comment]
Closed for inactivity.
